### ISSUE TITLE
Only works in the U.S.?

### ISSUE THREAD

**Issue by jimsynz** [silasbw/pebble_marine#1]
I loaded this app on my pebble thinking it'd come in handy while sailing but it never displays any information. I realise that some of the features might not work without any NOAA stations nearby but it'd still be great to have speed and bearing. 
I've not written any Pebble apps but the SDK example, but I'm happy to help if I can.

**Comment by jimsynz** [comment]
(Oh, I'm in New Zealand)

**Comment by silasbw** [comment]
pebble_marine requires a bluetooth connection to your phone (to use the GPS).  I should make this clear in the README.md and in the app store.  Do you sail with your phone?  If that's the case do lat, lng show up on the status window (hold the middle select button on the watch)?

**Comment by jimsynz** [comment]
Yes, I take my phone (iPhone 6) when I go sailing in a waterproof case. It doesn't work on land either.  Should it should my LAT/LNG and 0kt speed when I use on land?

Here's a quick video of me trying to use it: https://vimeo.com/124681903

**Comment by silasbw** [comment]
Thanks @jamesotron.  I wasn't able to scrounge up an iphone, but I improved the phone-watch communication code and added more verbose logging (311aa396e4191f07f2bc16544df0c7c036f1101d).  I also released a new version of the Pebble marine to the app store.  If the new version still doesn't work for you, and you want to get your hands dirty, try building and installing Pebble marine, and inspecting the logs.  For me they look like:

[INFO    ] D main.c:382 sync_changed_handler(4969): 1, 0.0
[INFO    ] D main.c:382 sync_changed_handler(4970): 2, 58
[INFO    ] D main.c:382 sync_changed_handler(4971): 3, 0.4
[INFO    ] D main.c:382 sync_changed_handler(4972): 4, 6
[INFO    ] D main.c:382 sync_changed_handler(4973): 5, H237
[INFO    ] D main.c:382 sync_changed_handler(4974): 6, 37.82033
[INFO    ] D main.c:382 sync_changed_handler(4975): 7, -122.25052
[INFO    ] D main.c:382 sync_changed_handler(4976): 8, Oakland Outer Harbor LB3
[INFO    ] D main.c:382 sync_changed_handler(4977): 9, Oakland Inner Harbor

**Comment by jhoc2000** [comment]
It doesn't work in Australia, probably because Australia is too far from NOAA stations. 

Please correct me if I'm wrong. I'd like to be able to use this whilst kayaking.

**Comment by silasbw** [comment]
You're correct, it's too far from NOAA stations.  If there's an API for
polling Australian weather stations (similar to the NOAA CO-OPS API), I'd
consider adding support.

Silas

**Comment by jhoc2000** [comment]
Hi Silas, 

Australia's official weather organisation is the Bureau of Meteorology (BoM). I don't know if they have an API but there is an app that shows BoM information called "Weather Australia". You may get more information by looking at that. 

There's also an existing Pebble tides notification app called "Tides aware (non-US) that will show the nearest tidal information. 

I don't know about API's but I hope that this will help you and consequently me. :--) 

John.
